services:
  - type: web
    name: home-credit-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
