"""
Compares class_weight="balanced" (no resampling) against SMOTE for handling
the ~8%/92% class imbalance in this dataset, under fold-safe 5-fold stratified
cross-validation (resampling wrapped in an imblearn Pipeline so it only ever
touches the training fold of each split — the opposite of the leakage this
project's validation rework removed).

Both options use the same fixed, reasonable LightGBM hyperparameters (the
`lightgbm_defaults` from params.yaml) rather than a full Optuna search per
option, since the question here is "does resampling help at all", not "what
are the best possible hyperparameters for each" — that search already runs
separately for whichever method params.yaml selects.

Writes reports/sampling_comparison.md with the measured results.

Usage: python scripts/compare_sampling.py
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

import pandas as pd
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold, cross_validate

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from src.config import DATA_PROCESSED, PARAMS, RANDOM_STATE, TARGET_COL  # noqa: E402

N_FOLDS = 5
SCORING = ["roc_auc", "average_precision"]


def _base_lgbm_params() -> dict:
    p = dict(PARAMS["lightgbm_defaults"])
    p.pop("class_weight", None)
    p["random_state"] = RANDOM_STATE
    p["n_jobs"] = -1
    p["verbose"] = -1
    return p


def _evaluate(estimator, X, y, label: str) -> dict:
    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)
    start = time.time()
    scores = cross_validate(estimator, X, y, cv=skf, scoring=SCORING, n_jobs=1)
    elapsed = time.time() - start
    result = {
        "label": label,
        "elapsed_s": round(elapsed, 1),
    }
    for metric in SCORING:
        vals = scores[f"test_{metric}"]
        result[metric] = {"mean": round(float(vals.mean()), 4), "std": round(float(vals.std()), 4)}
    return result


def main():
    df = pd.read_parquet(DATA_PROCESSED / "train_features.parquet")
    feature_cols = [c for c in df.columns if c not in ("SK_ID_CURR", TARGET_COL)]
    X = df[feature_cols].values
    y = df[TARGET_COL].values
    print(f"Training partition: {X.shape[0]} rows, {X.shape[1]} features, "
          f"{y.mean():.4f} default rate")

    class_weight_model = LGBMClassifier(class_weight="balanced", **_base_lgbm_params())
    smote_pipeline = ImbPipeline([
        ("resample", SMOTE(
            sampling_strategy=PARAMS["sampling"]["sampling_strategy"],
            k_neighbors=PARAMS["sampling"]["k_neighbors"],
            random_state=RANDOM_STATE,
        )),
        ("model", LGBMClassifier(**_base_lgbm_params())),
    ])

    print("Running class_weight='balanced' (no resampling)...")
    result_cw = _evaluate(class_weight_model, X, y, "class_weight=balanced (no resampling)")
    print(result_cw)

    print("Running SMOTE (fold-safe, inside Pipeline)...")
    result_smote = _evaluate(smote_pipeline, X, y, "SMOTE (fold-safe)")
    print(result_smote)

    better_auc = result_cw if result_cw["roc_auc"]["mean"] >= result_smote["roc_auc"]["mean"] else result_smote

    report = f"""# Sampling-method comparison: class_weight vs. SMOTE

Generated by `scripts/compare_sampling.py` against the real training
partition (`data/processed/train_features.parquet`, {X.shape[0]} rows,
{y.mean():.4f} default rate), under {N_FOLDS}-fold stratified cross-validation.
Resampling is wrapped in an `imblearn.pipeline.Pipeline` so SMOTE is fit and
applied only inside each training fold, never on the held-out fold of that
split — the fold-safe equivalent of the leakage this project's validation
rework removed from the Optuna search. Both methods share identical LightGBM
hyperparameters (`lightgbm_defaults` from `params.yaml`); this is a sampling
comparison, not a hyperparameter search.

| Method | ROC-AUC (mean ± std) | Average Precision (mean ± std) | CV wall time |
|---|---|---|---|
| {result_cw['label']} | {result_cw['roc_auc']['mean']} ± {result_cw['roc_auc']['std']} | {result_cw['average_precision']['mean']} ± {result_cw['average_precision']['std']} | {result_cw['elapsed_s']}s |
| {result_smote['label']} | {result_smote['roc_auc']['mean']} ± {result_smote['roc_auc']['std']} | {result_smote['average_precision']['mean']} ± {result_smote['average_precision']['std']} | {result_smote['elapsed_s']}s |

## Decision

**Default: `sampling.method: none` (class_weight="balanced")**, per
`params.yaml`.

On this comparison, `{better_auc['label']}` reached the higher mean ROC-AUC.
Independent of which one scores marginally higher, `class_weight="balanced"`
is preferred as the default because:

- It does not fabricate synthetic feature vectors, so it cannot distort the
  distribution of engineered ratios that later get probability-calibrated —
  calibration is sensitive to exactly this kind of distributional shift.
- It adds no extra hyperparameters (`sampling_strategy`, `k_neighbors`) that
  would otherwise need tuning on top of the LightGBM search.
- It is deterministic given the data (no synthetic-sample random draw), which
  keeps runs reproducible with one fewer source of randomness.

SMOTE remains available (`sampling.method: smote` in `params.yaml`) and,
since it now runs inside a fold-safe `imblearn.Pipeline` both in this
comparison and in the Optuna search itself (see `src/models/train.py`), it
can be re-enabled and tuned without reintroducing the cross-validation
leakage this project's validation-strategy rework removed.
"""
    (ROOT / "reports").mkdir(exist_ok=True)
    (ROOT / "reports" / "sampling_comparison.md").write_text(report, encoding="utf-8")
    print("Report written to reports/sampling_comparison.md")


if __name__ == "__main__":
    main()
